# Generated by Django 5.0.1 on 2024-02-03 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_accountmodel_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
