# Generated by Django 5.0.1 on 2024-02-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accountmodel_created_at_alter_accountmodel_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountowenrmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
