# Generated by Django 5.0.1 on 2024-02-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accountmodel_created_at_alter_accountmodel_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='blocked_until',
            field=models.DateField(null=True),
        ),
    ]
