# Generated by Django 5.0.1 on 2024-02-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_accountmodel_blocked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='blocked_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
