# Generated by Django 5.0.1 on 2024-02-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_accountmodel_blocked_until'),
        ('account', '0005_alter_accountowenrmodel_user'),
    ]

    operations = [
    ]
