# Generated by Django 5.0.1 on 2024-02-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_merge_20240204_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
