# Generated by Django 5.0.1 on 2024-02-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_accountmodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountowenrmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
